name: Python Code Improvements

on: push 

jobs:
  code_improvement:
    name: Code Improvement
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.*'

      - name: Install Dependencies 
        run: pip install --upgrade pip && pip install autopep8 autoflake black flake8 isort

      - name: Check missing code with flake8 
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Autopep8 to fix syntax and tokenize
        run: autopep8 --verbose --in-place --recursive --aggressive --aggressive --ignore=W605 . --exclude __init__.py

      - name: Remove unused imports and variables
        run: autoflake --in-place --recursive --remove-all-unused-imports --remove-unused-variables --ignore-init-module-imports .

      - name: Format code with Black
        run: black . --line-length 128

      - name: Sort imports with isort
        run: isort . --line-length 128

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "`something`"
